#!/usr/bin/env python
#-*- coding: utf-8 -*-


import rospy
from ar_track_alvar_msgs.msg import AlvarMarkers
from turtlesim.msg import Pose
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
from enum import Enum
from tf.transformations import euler_from_quaternion
from math import degrees, radians, pi, cos, sin, asin, sqrt

class MarkerTracking:
    def __init__(self):
        pass


if __name__ == '__main__':
    try:
        MarkerTracking()
        rospy.spin()
        
    except rospy.ROSInterruptException:  pass