#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from dynamic_reconfigure.server import Server
from turtlebot3_autorace_detect.cfg import DetectTrafficLightParamsConfig #

class SignDetector():
    def __init__(self):
        # step1. 색깔을 탐지하고
        # step2. 파란색이 탐지됐을 시, `carry_out_mission=True`로 변경
        # step3. 빨간색이 탐지됐을 시, `move_forward=False`로 변경하고 stop
        rospy.sleep(1)

        loop_rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            if self.is_image_available == True:
                self.fnFindSign()

            loop_rate.sleep()

    def fnFindSign(self):
        pass

    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('sign_detector')
    node = SignDetector()
    node.main()